#!/bin/sh
set -eu

repository_root="$(git rev-parse --show-toplevel)"
for variable in $(git rev-parse --local-env-vars); do
  unset "$variable"
done
cd "$repository_root"

echo "strategos: running pre-commit checks"
npm run check
